CREATE TABLE "user" (id text PRIMARY KEY,name text NOT NULL,email text NOT NULL UNIQUE,email_verified boolean NOT NULL DEFAULT false,image text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),role text NOT NULL DEFAULT 'reader' CHECK(role IN ('reader','editor','maintainer')),suspended boolean NOT NULL DEFAULT false);
CREATE TABLE session(id text PRIMARY KEY,expires_at timestamptz NOT NULL,token text NOT NULL UNIQUE,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,ip_address text,user_agent text,user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE);
CREATE INDEX session_user_idx ON session(user_id);
CREATE TABLE account(id text PRIMARY KEY,account_id text NOT NULL,provider_id text NOT NULL,user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,access_token text,refresh_token text,id_token text,access_token_expires_at timestamptz,refresh_token_expires_at timestamptz,scope text,password text,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE verification(id text PRIMARY KEY,identifier text NOT NULL,value text NOT NULL,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX verification_identifier_idx ON verification(identifier);
CREATE TABLE rate_limit(id text PRIMARY KEY,key text NOT NULL UNIQUE,count integer NOT NULL,last_request bigint NOT NULL);
CREATE TABLE authors(id text PRIMARY KEY,slug text NOT NULL UNIQUE,name text NOT NULL,bio text,portrait_id text);
CREATE TABLE posts(id text PRIMARY KEY,slug text NOT NULL UNIQUE,status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','unpublished')),draft_revision_id text,published_revision_id text,version integer NOT NULL DEFAULT 0,created_by text NOT NULL REFERENCES "user"(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz,search_text text NOT NULL DEFAULT '');
CREATE TABLE revisions(id text PRIMARY KEY,post_id text NOT NULL REFERENCES posts(id) ON DELETE CASCADE,content jsonb NOT NULL,created_by text NOT NULL REFERENCES "user"(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX revision_post_idx ON revisions(post_id);
CREATE TABLE media(id text PRIMARY KEY,filename text NOT NULL,original_path text NOT NULL,path text NOT NULL,small_path text NOT NULL,width integer NOT NULL,height integer NOT NULL,alt text NOT NULL DEFAULT '',caption text NOT NULL DEFAULT '',credit text NOT NULL DEFAULT '',created_by text NOT NULL REFERENCES "user"(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE placements(slot text PRIMARY KEY CHECK(slot IN ('lead','poem','art')),post_id text REFERENCES posts(id) ON DELETE SET NULL);
CREATE TABLE comments(id text PRIMARY KEY,post_id text NOT NULL REFERENCES posts(id),user_id text NOT NULL REFERENCES "user"(id),body text NOT NULL CHECK(length(body) BETWEEN 1 AND 4000),status text NOT NULL DEFAULT 'visible' CHECK(status IN ('visible','removed','deleted','pending')),created_at timestamptz NOT NULL DEFAULT now(),removed_by text REFERENCES "user"(id));
CREATE INDEX comment_post_idx ON comments(post_id,created_at);
CREATE TABLE moderation(id text PRIMARY KEY,comment_id text REFERENCES comments(id),target_user_id text REFERENCES "user"(id),actor_id text NOT NULL REFERENCES "user"(id),action text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE limits(key text PRIMARY KEY,count integer NOT NULL,reset_at timestamptz NOT NULL);
CREATE TABLE redirects(slug text PRIMARY KEY,post_id text NOT NULL REFERENCES posts(id));
ALTER TABLE posts ADD CONSTRAINT draft_revision_fk FOREIGN KEY(draft_revision_id) REFERENCES revisions(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE posts ADD CONSTRAINT published_revision_fk FOREIGN KEY(published_revision_id) REFERENCES revisions(id) DEFERRABLE INITIALLY DEFERRED;
